version: '3.4'

services:
  GLeadGenerator.api:
    image: ${DOCKER_REGISTRY-}bitmouseleadgeneratorapi
    container_name: GLeadGenerator.Api
    build:
      context: .
      dockerfile: GLeadGenerator.Api/Dockerfile
    ports:
        - 5000:80
        - 5001:443
    networks:
        - integration
        - database

  GLeadGenerator.integration.api:
    image: ${DOCKER_REGISTRY-}bitmouseleadgeneratorintegrationapi
    container_name: GLeadGenerator.Integration.Api
    build:
      context: .
      dockerfile: GLeadGenerator.Integration.Api/Dockerfile
    ports:
        - 5002:80
        - 5003:443
    networks:
        - integration

  GLeadGenerator.database:
    image: ${DOCKER_REGISTRY-}bitmouseleadgeneratordatabase
    build:
      context: .
      dockerfile: GLeadGenerator.Database/Dockerfile
    container_name: GLeadGenerator.Database
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=E8!49NaJXRFYvE2qRm7m4YD8cfoEy7F
    ports:
        - 1433:1433
    restart: unless-stopped
    volumes:
        - ~/apps/mssql/data:/var/lib/mssqlql/data
    networks:
        - database

networks:
  integration:
  database:

volumes:
  database-data:
